### ISSUE TITLE
Why can't I find the package tkan?

### ISSUE THREAD

**Issue by 123456789qwerfds** [remigenet/TKAN#13]
(CAD) xsl@xsl:~$ pip install tkan
ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python <4.0,>=3.10; 0.1.1 Requires-Python <4.0,>=3.10; 0.1.2 Requires-Python <4.0,>=3.10; 0.2.0 Requires-Python <4.0,>=3.10; 0.3.0 Requires-Python <4.0,>=3.9; 0.4.0 Requires-Python <3.12,>=3.9; 0.4.1 Requires-Python <3.12,>=3.9; 0.4.2 Requires-Python <3.13,>=3.9
ERROR: Could not find a version that satisfies the requirement tkan (from versions: none)
ERROR: No matching distribution found for tkan

**Comment by remigenet** [comment]
I guess your python version is too old, you are probably in bellow python 3.9 which is minimum version for the package as it is in keras3 that requires python >= 3.9 !

**Comment by 123456789qwerfds** [comment]
Thank you for your answer, I have successfully solved this problem.

**Comment by Adele0108** [comment]
Hello, have you run the code successfully? Could you tell me the version requirements of the tensorflow, keras and other packages? Thanks!
