### ISSUE TITLE
Error: Packages Version

### ISSUE THREAD

**Issue by Adele0108** [remigenet/TKAN#16]
`  File "/opt/conda/envs/tf-gpu/lib/python3.9/site-packages/keras/src/utils/dataset_utils.py", line 9, in <module>
    from keras.src import tree
  File "/opt/conda/envs/tf-gpu/lib/python3.9/site-packages/keras/src/tree/__init__.py", line 1, in <module>
    from keras.src.tree.tree_api import assert_same_structure
  File "/opt/conda/envs/tf-gpu/lib/python3.9/site-packages/keras/src/tree/tree_api.py", line 6, in <module>
    from keras.src.tree import optree_impl as tree_impl
  File "/opt/conda/envs/tf-gpu/lib/python3.9/site-packages/keras/src/tree/optree_impl.py", line 17, in <module>
    from tensorflow.python.trackable.data_structures import ListWrapper
ModuleNotFoundError: No module named 'tensorflow.python.trackable'`

I have installed the tensorflow-gpu= 2.4.1 and keras=3.6.0. Could you tell me the version of the tensorflow, keras, python, tkan and other packages or release the requirement file? Thanks!

**Comment by remigenet** [comment]
Tensorflow 2.4.1 is a quite old version I think and probably not supported by keras
I don't even think tensorflow-gpu is anymore updated, I think that now you either need latest tensorflow for Nvidia GPU or can use tensorflow-rocm for AMD card (still I had many issues with it in the past, not sure how it is currently..) 
That's not related to the TKAN package as it only uses keras interface and is backend agnostic, which means you can use any keras backend
Thus a first way to solve could maybe be uninstall tensorflow-gpu and install latest tensorflow with pip
Another option is to use Jax backend (better performance and I have less issue with it personally), so just install Jax (or jax cuda version if you have an Nvidia card) and specify backend at the beginning 
The exemple in the exemple folder shows an example of how to ! (Still you need to have all cuda drivers install if you want to use GPU of course)
