### ISSUE TITLE
TKAN doesn't work while loading pre-trained weights

### ISSUE THREAD

**Issue by duc-an-nguyen** [remigenet/TKAN#17]
Hi, It seems like the TKAN has some problems loading the saved weight. Because every time I load a checkpoint, it always shows something like: The shape of the target variable and the shape of the target value in variable.assign(value)` must match. variable.shape=(1, 10), Received: value.shape=(1, 10). Target variable: <KerasVariable shape=(1, 2, 10), dtype=float32, path=tkan_6/tkan_cell_6/kan_linear_6/grid>

List of objects that could not be loaded:
[, , , ]`
I tested in many ways from loading .h5 file to using default keras. All of them don't work at all.
I noticed that there was another opened issue before, but it hadn't been fixed in the new version of TKAN 0.4.2. Has anyone faced the same problem?

**Comment by remigenet** [comment]
Same as https://github.com/remigenet/TKAN/issues/15#issuecomment-2412104966
