### ISSUE TITLE
signed_softmax? 

### ISSUE THREAD

**Issue by luoolu** [remigenet/TKAN#2]
how to use this fun?

**Comment by remigenet** [comment]
Hi, that was just a custom activation function from another project I copied there, you can just use any activation function, here as it's a dense layer (so no value would results in a linear activation, you can use 'relu' or any name from tensorflow documentation, or in fact any callable here (or one of the spline activation from the package).
I am going to just remove it from the README to avoid confusion, and give a more complete example, thanks for pointing it out

**Comment by luoolu** [comment]
thanks

**Comment by remigenet** [comment]
Hi, README is corrected and I added an example notebook based on what we used for the paper to show how to use it !
