### ISSUE TITLE
Neural network settings

### ISSUE THREAD

**Issue by kkkkcccc88** [remigenet/TKAN#20]
Why are sub_kan_output_dim and sub_kan_input_dim set to 50 in the code, can they be set arbitrarily?

**Comment by remigenet** [comment]
They are for example, and yes they can be set arbitrarily - default value use the input shape but you can change them with this parameter 
sub_kan_input_dim will impact the dimension of the input fed to RKAN layers, by a linear transformation of the inputs (and state size)
sub_kan_output_dim will impact the size of the KAN layers inside the RKAN

**Comment by kkkkcccc88** [comment]
So, in an RKAN, there are independent KAN layers without connections between them, and according to the code you provided, there is only one KAN layer. Is that understanding correct?

**Comment by kkkkcccc88** [comment]
Is the input and output of KAN the same as the input and output of RKAN?Below is a diagram that I  have drawn based on my own understanding. Could you please check if my  understanding is correct? Thank you.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "remigenet/TKAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月7日(星期六) 上午7:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [remigenet/TKAN] Neural network settings (Issue #20)





 
They are for example, and yes they can be set arbitrarily - default value use the input shape but you can change them with this parameter
 sub_kan_input_dim will impact the dimension of the input fed to RKAN layers, by a linear transformation of the inputs (and state size)
 sub_kan_output_dim will impact the size of the KAN layers inside the RKAN

**Comment by remigenet** [comment]
I can't see the diagram, you probably forgot to include the image?!
But to explain no they are not quite the same, in fact at a given timestep :
the RKAN receive the layer input that is shape (batch, features) and the previous state that is shape (batch, kan_output_size) 
It will first compute inputs * sub_tkan_recurrent_kernel_inputs (their is one kernel like this for each RKAN) -> multiplication output shape is (batch, kan_input_dim)
I will also compute past_state * sub_tkan_recurrent_kernel_states (again one different kernel for each RKAN) -> multiplication output shape is also  (batch, kan_input_dim)
This two results are then summed together (term at term as they are the same shape) and this is passed to the KAN layer which output will be (batch, kan_output_shape)
This output is the RKAN output that is used by the TKAN afterwards, and is also used to create the new current state of the RKAN
To create the new current state we just multiply the output by a first kernel, and the last state by another kernel (keeping the dimension in (batch, kan_output) and then summing this two

I hope that's more clear

**Comment by kkkkcccc88** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "remigenet/TKAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月9日(星期一) 凌晨3:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [remigenet/TKAN] Neural network settings (Issue #20)

I apologize for the direct screenshot that apparently couldn't be  displayed. Now I'm sending it as a file; please see if you can view it.  Regarding sub_kan_input_dim and sub_kan_output_dim being multiplied by 2, it's because both x and sub_state have to go through the KAN layer to undergo the same operations. Is there any issue with my understanding? Thank you.


 
I can't see the diagram, you probably forgot to include the image?!
 But to explain no they are not quite the same, in fact at a given timestep :
 the RKAN receive the layer input that is shape (batch, features) and the previous state that is shape (batch, kan_output_size)
 It will first compute inputs * sub_tkan_recurrent_kernel_inputs (their is one kernel like this for each RKAN) -&gt; multiplication output shape is (batch, kan_input_dim)
 I will also compute past_state * sub_tkan_recurrent_kernel_states (again one different kernel for each RKAN) -&gt; multiplication output shape is also  (batch, kan_input_dim)
 This two results are then summed together (term at term as they are the same shape) and this is passed to the KAN layer which output will be (batch, kan_output_shape)
 This output is the RKAN output that is used by the TKAN afterwards, and is also used to create the new current state of the RKAN
 To create the new current state we just multiply the output by a first kernel, and the last state by another kernel (keeping the dimension in (batch, kan_output) and then summing this two
 
I hope that's more clear

**Comment by kkkkcccc88** [comment]
I apologize for the direct screenshot that apparently couldn't be displayed. Now I'm sending it as a file; please see if you can view it. Regarding sub_kan_input_dim and sub_kan_output_dim being multiplied by 2, it's because both x and sub_state have to go through the KAN layer to undergo the same operations.Is there any issue with my understanding? Thank you.
[新建 Microsoft Word 文档 (4).docx](https://github.com/user-attachments/files/18055813/Microsoft.Word.4.docx)
