### ISSUE TITLE
ImportError: cannot import name 'BSplineActivation' from 'tkan' (/usr/local/lib/python3.10/dist-packages/tkan/__init__.py)

### ISSUE THREAD

**Issue by wuhyyy** [remigenet/TKAN#5]
from tkan import BSplineActivation
have an ImportError today,but I run it successfully in the day before yesterday.Did you delete it ?
ImportError: cannot import name 'BSplineActivation' from 'tkan' (/usr/local/lib/python3.10/dist-packages/tkan/__init__.py)

**Comment by remigenet** [comment]
Hi, last pypi package version is the one from the beta branch (going to be merged soon), that changed it a bit to match efficient_kan KAN implementation, to use it refers to the documentation on beta or specify tkan==0.2.0 when installing !

**Comment by wuhyyy** [comment]
oh,I see,it is the version problem,thank you
