### ISSUE TITLE
Can we implement a PyTorch version? The TensorFlow version has many GPU compatibility issues

### ISSUE THREAD

**Issue by luoolu** [remigenet/TKAN#7]
such like this:
libdevice not found at ./libdevice.10.bc
	 [[{{node StatefulPartitionedCall}}]] [Op:__inference_one_step_on_iterator_64513]

Process finished with exit code 1

**Comment by wangyb97** [comment]
I also want the PyTorch version, which will be very helpful!

**Comment by remigenet** [comment]
My co-author plans to add one, as he is more used to torch while I am more in tensorflow, still he don't have much bandwidth for the moment so no ETA given for now. That said, if any wants to propose a torch implementation I can merge it in the repo after checking with pleasure.

**Comment by Summer-77** [comment]
I would like to know what is the version of Tensorflow?

**Comment by remigenet** [comment]
Hi, for version 0.2.0 it has been checked compatible for 2.8 to 2.16, for 0.3.0 I developped it in 2.16 (latest) and I believe this should be working with same version as before (still, I haven't checked)

**Comment by Summer-77** [comment]
> Hi, for version 0.2.0 it has been checked compatible for 2.8 to 2.16, for 0.3.0 I developped it in 2.16 (latest) and I believe this should be working with same version as before (still, I haven't checked)

thank you

**Comment by remigenet** [comment]
tkan 0.4.0 (beta_2  branch on github) now relies fully on keras and is thus multi-backend (tf, torch, jax) 
However, I am not sure the torch version is using GPU and is thus much much slower than the 2 other alternatives (tf and jax works perfect for GPU)

**Comment by remigenet** [comment]
The new version has been tested and is now merged on main ! Closing the issue
